### ISSUE TITLE
Parsing failure for tls_record.rflx

### ISSUE THREAD

**Issue by urbasus** [Componolit/RecordFlux-specifications#19]
I tried parsing the tls_record.rflx example and get this result:

```
$ rflx generate ../tls_record.rflx
Parsing ../tls_record.rflx
../tls_record.rflx:13:21: parser: error: Expected {{"First" - "=>" - MathematicalExpression} | {"Length" - "=>" - MathematicalExpression}}
```

Using rflx v0.4.1, Python 3.7.3.

**Comment by senier** [comment]
Hi @urbasus,

thanks for your ticket.

The error you observe is due to syntax changes introduced in the current development version of RecordFlux. Specifications in this repository are (potentially) incompatible with the 0.4.1 release. They will be compatible with the upcoming 0.5 release, though (we will also create a release of this specification repository and tag it properly).

For the time being you should install the development version of RecordFlux if you want to play with the specs contained in here, e.g. by doing

```
$ pip install RecordFlux@git+https://github.com/Componolit/RecordFlux.git@develop
```

Don't hesitate to open further tickets should you have questions or get in trouble with `develop`.

**Comment by senier** [comment]
Closing as this is expected.
